name: Lint PR

on:
  pull_request_target:
  push:
    branches:
      - master

jobs:
  file-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}

      # This will lint all files, see https://github.com/timhagn/lint-md-fm
      - name: Lint Current PR
        id: lint
        uses: timhagn/lint-md-fm@v1.2.6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          changed-files: ""
          directories: |
            projects
            img
          markdown-extensions: |
            .md
            .mdx
          image-extensions: |
            .png
            .svg
            .jpg
            .jpeg

      # Use the output from the `lint` step
      - name: Display changed files
        run: echo "Changed files are ${{ steps.lint.outputs.changed }}"
